### ISSUE TITLE
Add missing items to GUI

### ISSUE THREAD

**Issue by vooku** [vooku/skinny#22]
- [x] MIDI setup
- [ ] ~~scene loading problems~~ #55 
- [ ] ~~general error reporting & logging~~ #55 
- [ ] ~~Resolution / framebuffer size?~~ #1
